### PR TITLE
doesn't work

### PR DESCRIPTION
**Pull request by gstrk**
when I try to start the game with the current version of the hack, the screen just turns green

### CODE REVIEW

**Comment by humphreygaming** [comment]
CTRL F5 (chromebook is CTRL and R) to clear all cache stored (and PLEASE, be patient and let all the surviv assets load)

**Comment by mlachowski-stx** [comment]
It don't help. Still not working.

**Comment by gstrk** [comment]
still doesn't work, hack needs to be updated

**Comment by humphreygaming** [comment]
we get it, stop reminding iblissin

**Pull request closed without merging**
